### ISSUE TITLE
为乱码创建字体

### ISSUE THREAD

**Issue by Physics365** [Physics365/991CN-X-CW-Decompilation#10]
为字符表乱码创建字体 @Wenti-D ，就像FA区中的那样（只不过那是图片）
比如表中的`$7B` (**FA**50)
![屏幕截图 2024-04-01 230140](https://github.com/Physics365/991CN-X-CW-Decompilation/assets/154725076/e083652a-c5ec-49c7-b9c4-02308fa6862a)

**Comment by Wenti-D** [comment]
在显示字体制作之初我已经想过相关的问题，一种做法是把乱码均还原出来，另一种做法是使用一个特定字符来「标记乱码」。权衡利弊之后，目前字体中采用了后者，即使用 U+2592「阴影」来替代所有乱码字符。

这样做是因为将每个乱码都做出来不太现实，且会增加字体中无意义码位的数量。但这种方式的弊端也很明显，就是「不够还原」。总之附上我没事排的字符表 PDF 文件，其中一级字符表 `FB60` 中就有 U+2592「阴影」的用例。
[CharaTable.pdf](https://github.com/Physics365/991CN-X-CW-Decompilation/files/14826166/CharaTable.pdf)

如果觉得如此用法可以的话，依葫芦画瓢即可。如果觉得还原乱码更好的话那我再想想对策。
