### ISSUE TITLE
建议不要把pdf打包到git内

### ISSUE THREAD

**Issue by qiufuyu123** [Physics365/991CN-X-CW-Decompilation#14]
pdf为二进制格式文件，git无法追踪变化
并且体积较大，会增加git pull / git clone  的时间负担

建议所有文档仅保留一份 .md 版本

**Comment by Wenti-D** [comment]
现在所有的 PDF 文件均标记为 LFS，若有更改，Git 不会存储每一份本体。应该能减小不必要的开销。

**Comment by qiufuyu123** [comment]
ok
