### ISSUE TITLE
教程格式讨论

### ISSUE THREAD

**Issue by EwTE-H** [Physics365/991CN-X-CW-Decompilation#16]
上下标、粗细体等等，用一般字体难以区分，对于读者也不易理解

**Comment by Physics365** [comment]
那这样的话使用Markdown就有点不方便了，建议使用Word，最后转成Markdown和PDF，因为Word使用字体方便，对更多人也友好一些。
你觉得如何？

并且还需要统一一下教程的格式（如正文字体，缩进，排版等）

**Comment by EwTE-H** [comment]
markdown内嵌html或者纯html可以吗

**Comment by Physics365** [comment]
可以的

**Comment by Physics365** [comment]
看一下temp.pdf，这个排版可以的话就按这个来吧。
修改方法：
* 安装“模拟器及资源/字体/文档字体/static”中的所有字体按键字体和显示字体
* 更改word.docx
* 打印，打印机选择Microsoft print to PDF(其他方法格式会乱)
![屏幕截图 2024-04-03 211351](https://github.com/Physics365/991CN-X-CW-Decompilation/assets/154725076/c9018dbd-ba3a-46f5-b735-f625a75bee42)
![屏幕截图 2024-04-03 211405](https://github.com/Physics365/991CN-X-CW-Decompilation/assets/154725076/d33fa965-ee54-400a-9c01-30a497ef9a01)

**Comment by Physics365** [comment]
以上是第一章的部分

**Comment by Wenti-D** [comment]
Noto Sans 默认行距过宽，中文标准行距应当是 1.2 倍字高（不要信 Word 的段落设置，那也是乱的），现在这是最大的问题。

**Comment by Wenti-D** [comment]
小四字号对于目前的内容来说可能太大，考虑改成 10 号（即五号）。

**Comment by Physics365** [comment]
![屏幕截图 2024-04-03 213203](https://github.com/Physics365/991CN-X-CW-Decompilation/assets/154725076/e93b3481-2022-4652-a8de-b81504c18308)
这样呢

**Comment by Physics365** [comment]
收到

**Comment by Wenti-D** [comment]
另外还有一些小问题：对齐方式设置为「两端对齐」而不是「左对齐」，目录应该不算第零章，以及考虑添加页码什么的，考虑多级目录什么的。

**Comment by Physics365** [comment]
这个我好像不全会弄，你看一下新增的zip包，你改一下吧（Word新手求助）😭😭😭

**Comment by Wenti-D** [comment]
呀，说实话，我是很少用 Word 排版的，因为调起来太复杂了，我要排版的话会用排版程序直接从源码生成 PDF 的……😂

**Comment by Physics365** [comment]
word里面我根本找不到某一级多级列表的行间距选项……
那这样的话应该怎么排版呢

**Comment by Wenti-D** [comment]
我本人排版用的是 LaTeX，不过要用 Word 的话当然也可以调，需要定义完善的样式。

**Comment by Physics365** [comment]
感谢，静等更新

**Comment by EwTE-H** [comment]
像FD 20这样的十六进制编码还是用一般的代码字体吧，只有对应“屏幕显示”的部分才用卡西欧字体

**Comment by ljm673** [comment]
字符编码写成这样怎么样？
![image](https://github.com/Physics365/991CN-X-CW-Decompilation/assets/78750425/21a8ba21-34e7-4623-8378-2413743026e5)

**Comment by Physics365** [comment]
我现在觉得用正常的ABCDEF即可，大家应该看得懂的

**Comment by Wenti-D** [comment]
> 字符编码写成这样怎么样？ ![image](https://private-user-images.githubusercontent.com/78750425/319234543-21a8ba21-34e7-4623-8378-2413743026e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxNTY4MjIsIm5iZiI6MTcxMjE1NjUyMiwicGF0aCI6Ii83ODc1MDQyNS8zMTkyMzQ1NDMtMjFhOGJhMjEtMzRlNy00NjIzLTgzNzgtMjQxMzc0MzAyNmU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDE1MDIwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwY2UzZWQ5N2M5MjY1NjEyNjk4YWQ0NDY1NDU4MjQ1MzlmZTYxODM0MDJjN2MyZDM0ODU3YTkxZTJmMjI3MDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.39mKRqEdyzmah_WHWcZJ92k-903wKm89pZDf8cPBT4s)

双字节怎么办（

**Comment by ljm673** [comment]
我是说把编码写在字符上方，而不是右边
对比一下
![image](https://github.com/Physics365/991CN-X-CW-Decompilation/assets/78750425/b6edc2ac-a9ba-4fee-8106-322268e5ad42)
至于十六进制数字，用正常的ABCDEF也可以
双字节：
![image](https://github.com/Physics365/991CN-X-CW-Decompilation/assets/78750425/b5a7f615-18b6-4848-8d74-e42d052559f4)

**Comment by EwTE-H** [comment]
> 字符编码写成这样怎么样？ ![image](https://private-user-images.githubusercontent.com/78750425/319234543-21a8ba21-34e7-4623-8378-2413743026e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxNTkyNjksIm5iZiI6MTcxMjE1ODk2OSwicGF0aCI6Ii83ODc1MDQyNS8zMTkyMzQ1NDMtMjFhOGJhMjEtMzRlNy00NjIzLTgzNzgtMjQxMzc0MzAyNmU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDE1NDI0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyZWNjN2U2YmVmMDE4NjhmMTAxY2IwZTczMTYzMWQyMGNhMDY0ZWYyZmM5MzYxOWRmYzYzOTZmMmZmODZjNjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dejVIoRPNH9tsXapn7g3WgisHgMHvfZ0CJFoyuYQ9zo)

不太好，第一，可能导致字符边界不清（比如你这个例子里的括号到底跟根号还是跟@就一眼看不出，碰到一坨一坨的乱码字符就更加乱了），第二，编码太小了略微费眼，第三，零宽度字符怎么办
另外编码部分建议使用其他字体以示区分

**Comment by Wenti-D** [comment]
> 不太好，第一，可能导致字符边界不清（比如你这个例子里的括号到底跟根号还是跟@就一眼看不出，碰到一坨一坨的乱码字符就更加乱了），第二，编码太小了略微费眼，第三，零宽度字符怎么办 另外编码部分建议使用其他字体以示区分

关于这个问题我以前也想过，等会传一张样本上来。

**Comment by EwTE-H** [comment]
> 字符编码写成这样怎么样？ ![image](https://private-user-images.githubusercontent.com/78750425/319234543-21a8ba21-34e7-4623-8378-2413743026e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxNTkyNjksIm5iZiI6MTcxMjE1ODk2OSwicGF0aCI6Ii83ODc1MDQyNS8zMTkyMzQ1NDMtMjFhOGJhMjEtMzRlNy00NjIzLTgzNzgtMjQxMzc0MzAyNmU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDE1NDI0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyZWNjN2U2YmVmMDE4NjhmMTAxY2IwZTczMTYzMWQyMGNhMDY0ZWYyZmM5MzYxOWRmYzYzOTZmMmZmODZjNjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dejVIoRPNH9tsXapn7g3WgisHgMHvfZ0CJFoyuYQ9zo)

不太好，第一，可能导致字符边界不清（比如你这个例子里的括号到底跟根号还是跟@就一眼看不出，碰到一坨一坨的乱码字符就更加乱了），第二，编码太小了略微费眼，第三，零宽度字符怎么办
另外编码部分建议使用其他字体以示区分

**Comment by Wenti-D** [comment]
图来！

![image](https://github.com/Physics365/991CN-X-CW-Decompilation/assets/73067578/6e59e528-17fd-40ad-ae9f-b2c1584e2756)

**Comment by ljm673** [comment]
挺好，LaTeX写的吧
第一行字符间距可以大一点，相邻下划线间的空隙不太清楚
我对LaTeX不太熟练，不太会写

**Comment by Wenti-D** [comment]
> 第一行字符间距可以大一点，相邻下划线间的空隙不太清楚

我故意把间距设置为 1pt 了，为了防止字符间距看起来太大🤔

**Comment by Physics365** [comment]
这样挺好的呀

**Comment by Wenti-D** [comment]
问题就在于这不是 Word 弄出来的，我在 Word 里面用文本框试了一下，调成「嵌入型」和「四周型」环绕，得到的结果会是这样：
![image](https://github.com/Physics365/991CN-X-CW-Decompilation/assets/73067578/0d5a73ff-2231-42b1-b338-defe4bc0095e)
![image](https://github.com/Physics365/991CN-X-CW-Decompilation/assets/73067578/0da6c79a-4134-44c1-8d7f-a6241ae4aeaf)

似乎问题在于 Word 的行距没法自适应？

**Comment by ljm673** [comment]
可以用域+EQ指令
效果：
![image](https://github.com/Physics365/991CN-X-CW-Decompilation/assets/78750425/d72bbeca-8803-4329-8d17-71b53eae1734)
最下面是代码，选中的是域的部分

**Comment by Wenti-D** [comment]
扔了一个 Word 版的示例到云盘里。结果还是没有办法给表格上下加间距😡

**Comment by Physics365** [comment]
征求一下意见：这个表格是否应该用所有框线？

@Wenti-D 的式样：
![屏幕截图 2024-04-05 212532](https://github.com/Physics365/991CN-X-CW-Decompilation/assets/154725076/ddb79728-1368-44ad-bf91-1379bfaaa502)
所有框线的式样：
![屏幕截图 2024-04-05 212540](https://github.com/Physics365/991CN-X-CW-Decompilation/assets/154725076/7295d9c5-0919-470e-8e2a-ecc438329100)

**Comment by ljm673** [comment]
Wenti-D的感觉好看点😊

**Comment by Physics365** [comment]
ok,那不改了

**Comment by ljm673** [comment]
话说**云盘**在哪里

**Comment by Wenti-D** [comment]
见[讨论帖](https://github.com/Physics365/991CN-X-CW-Decompilation/discussions/19#discussioncomment-9006811)

**Comment by Physics365** [comment]
还有一个问题：标题3的缩进是特意设置的吗？这空的有点长啊

**Comment by Wenti-D** [comment]
显然……不是，可能我忘改了，也可能是 Word 抽风了，总之标题 2 及以下全部顶格的。

**Comment by Physics365** [comment]
![屏幕截图 2024-04-05 220251](https://github.com/Physics365/991CN-X-CW-Decompilation/assets/154725076/8a77dcd4-7b71-4d05-ad24-43a926ae0474)
这是需要的效果吗？是的话我在云盘里更新一下模板

**Comment by Wenti-D** [comment]
差不多就是这样了，6 到 9 级的应该不会使用吧。然后 2 至 4 级中间的空格可以均一以下就更好了。

**Comment by Physics365** [comment]
还有就是字符码最后我觉得可以统一多加两个00。（特殊情况除外）

**Comment by Physics365** [comment]
我觉得这个2~4级应该不用均一，因为实际使用几乎不可能会三级标题上下出现，单独出现时空太多反而影响美观

**Comment by Wenti-D** [comment]
我的意思是，要：
```
1.1  标题
1.1.1  标题
1.1.1.1  标题
```

而不是：
```
1.1        标题
1.1.1      标题
1.1.1.1    标题
```

也不是：
```
1.1     标题
1.1.1  标题
1.1.1.1   标题
```

**Comment by Physics365** [comment]
okok

**Comment by Physics365** [comment]
我竟不知道在哪里调

**Comment by Wenti-D** [comment]
在上方【段落】→【多级列表】→定义新的多级列表】里调。我传了个改过的上去了。

**Comment by Physics365** [comment]
第一章完成，在云盘里：新版教程.docx，但是我没改刚刚那个格式，请你帮忙改完再传一下

**Comment by Physics365** [comment]
![屏幕截图 2024-04-06 002446](https://github.com/Physics365/991CN-X-CW-Decompilation/assets/154725076/bad0a771-a9f9-4f80-a0b4-01da96112263)

**Comment by Physics365** [comment]
为什么新的模板是这样的
```
    1.1  标题2
      1.1.1  标题3
        1.1.1.1  标题4
```

**Comment by ljm673** [comment]
要把**自动调整右缩进**去掉
![image](https://github.com/Physics365/991CN-X-CW-Decompilation/assets/78750425/3ad391b1-3eb2-493e-bddb-ee1d6129502f)

**Comment by Wenti-D** [comment]
原来是这样吗

**Comment by Physics365** [comment]
并不是，rt

**Comment by Physics365** [comment]
你左侧缩进了1.4cm(2级)

**Comment by ljm673** [comment]
雀食😅

**Comment by Wenti-D** [comment]
我设置了以后，无论是保存为空模板还是将以下内容保存为模板：
![image](https://github.com/Physics365/991CN-X-CW-Decompilation/assets/73067578/ec587c23-ad93-41b0-ae69-99d8c9b2b268)

最终都会：
![image](https://github.com/Physics365/991CN-X-CW-Decompilation/assets/73067578/d86a9252-70c1-44d0-903a-d6c6f457b0fe)

我的评价是，模板功能烂中烂👎😅

**Comment by Physics365** [comment]
目录的显示级别改为2吧，不然太长了
![屏幕截图 2024-04-06 234403](https://github.com/Physics365/991CN-X-CW-Decompilation/assets/154725076/eafb0c10-9337-4515-ac04-d8b6651da0c2)
![屏幕截图 2024-04-06 234323](https://github.com/Physics365/991CN-X-CW-Decompilation/assets/154725076/06aa325a-26d5-4189-acb1-0b780a81262c)
![屏幕截图 2024-04-06 234114](https://github.com/Physics365/991CN-X-CW-Decompilation/assets/154725076/54ad7b25-4832-403b-b10d-e017f3fbff3f)

**Comment by Wenti-D** [comment]
这个以内容决定吧，甚至可以分两栏（如果一行够短的话）。
