### ISSUE TITLE
上传二进制文件时压缩为 ZIP

### ISSUE THREAD

**Issue by Wenti-D** [Physics365/991CN-X-CW-Decompilation#17]
目前的 LFS 配置已经在追踪 ZIP 文件，所以上传二进制文件（例如 Ghidra 的项目，Word 的模板等等）时预先压缩为 ZIP 文件再上传。否则仓库大小会爆炸的。

**Comment by Physics365** [comment]
好的（目前计划不再上传Ghidra Project）

**Comment by qiufuyu123** [comment]
感觉现在体积已经要爆炸了 (

**Comment by qiufuyu123** [comment]
感觉先把字体压一下，仓库里一个字体文件10mb

**Comment by Wenti-D** [comment]
然后真变基的话大伙必须要重新克隆，避免又合并上来原来的了。

**Comment by Wenti-D** [comment]
比如说，我今天 23:00（UTC+8）把变基结果推送，然后大伙重新克隆……什么的？

**Comment by Physics365** [comment]
收到

**Comment by Physics365** [comment]
你觉得如何让所有人都知道要重新克隆

**Comment by qiufuyu123** [comment]
这个只跟我们contributer有关，所以我们三个知道就行，其他人不push无所谓

**Comment by Wenti-D** [comment]
还有 @EwTE-H

**Comment by Wenti-D** [comment]
已经推送。

**Comment by Wenti-D** [comment]
有什么在变基过程中缺了的文件大家可以补充。

话说真的要把 Noto Sans 塞进来吗（

**Comment by Physics365** [comment]
算了吧，最后发PDF就没事了（

**Comment by Physics365** [comment]
> 但还是有近 100 M 的 LFS 文件，主要是某个大 PDF 吧…… 
这个是给新手的汇编教程

**Comment by Physics365** [comment]
这个《Assembly Language》也删了吧，太大了

**Comment by fish4terrisa-MSDSM** [comment]
这个《Assembly Language》有稳定的链接吗，也许可以在资料folder的README.md中加入一个下载链接来替代

**Comment by Wenti-D** [comment]
网盘里头有其实，在 `/nX-U8 指令集` 下。
