### ISSUE TITLE
将 Ghidra 本体换成指向其发布页的链接

### ISSUE THREAD

**Issue by Wenti-D** [Physics365/991CN-X-CW-Decompilation#2]
在仓库里带一个 400M+ 的软件本体似乎不是什么好事，而这东西在 GitHub 有发布页面：https://github.com/NationalSecurityAgency/ghidra/releases ，可以直接在这里下载到。

**Comment by Physics365** [comment]
OKOK,稍等一下

**Comment by Physics365** [comment]
我放本体的本意是本体里已经有了@EwTE_H的语言文件，免得大家再自己放，不过现在想来还是换了吧

**Comment by Wenti-D** [comment]
完善的文档可以用来指导大家操作吧，应该……
~~不排除有人硬是不看字~~

**Comment by Physics365** [comment]
README.md已修改更新，并删去了400MB😅的Ghidra文件夹
