### ISSUE TITLE
[BUG] casio.123a.club Bad gateway

### ISSUE THREAD

**Issue by fish4terrisa-MSDSM** [Physics365/991CN-X-CW-Decompilation#26]
https://casio.123a.club/ 出现了502 bad gateway
![image](https://github.com/Physics365/991CN-X-CW-Decompilation/assets/63049888/cc4f49d6-e0fa-4aa3-bf1d-7b89d880e7a9)

如上，建议存在其他更加稳定的地方(其实github的lfs并不差)(别放百度网盘或其他任何需要登陆的网盘，gofile也许不错)。或者如果有rsync的链接的话我也可以考虑放在我的cloudflare pages上。
P.S. 其实可以放在一个单独的repo以防影响的说

**Comment by Physics365** [comment]
或许可以放这里
[LFS仓库](https://github.com/Physics365/991CN-X-CW-Decompilation_Files)

**Comment by Wenti-D** [comment]
news: 网盘好了

**Comment by fish4terrisa-MSDSM** [comment]
看到了，lfs的repo也已更新。issue close
