### ISSUE TITLE
Persistence/data.asm 与 Persistence/DataPersistence.md内容矛盾

### ISSUE THREAD

**Issue by fish4terrisa-MSDSM** [Physics365/991CN-X-CW-Decompilation#29]
在 [Persistence/DataPersistence.md](https://github.com/fish4terrisa-MSDSM/991CN-X-CW-Decompilation/blob/main/ROP/ROPCodes/Examples/Persistence/DataPersistence.md) 中，其内容为”赋值给M变量“，但是[Persistence/data.asm](https://github.com/fish4terrisa-MSDSM/991CN-X-CW-Decompilation/blob/main/ROP/ROPCodes/Examples/Persistence/data.asm)中是

```asm
;(33) 34 3c 34 3f 35 36 32 30 35 39
; [3][4][C][4][F][5][6][2][0][5][9] -> B
```
所以到底是赋值给哪个变量？
顺带一提，[Persistence/DataPersistence.md](https://github.com/fish4terrisa-MSDSM/991CN-X-CW-Decompilation/blob/main/ROP/ROPCodes/Examples/Persistence/DataPersistence.md) 的描述很奇怪，让人分不清到底一次copy6个bytes还是4个（因为解析数据存储时是4个，而实际copy时写的是6个，可不可以把实际复制时的关键步骤，如赋值给M这一步的图片给出）
而且.可以把[Persistence/data.asm](https://github.com/fish4terrisa-MSDSM/991CN-X-CW-Decompilation/blob/main/ROP/ROPCodes/Examples/Persistence/data.asm)中哪一部分是地址在注释里指出吗，毕竟实际使用时基本不可能都copy到0xea30的说

**Comment by qiufuyu123** [comment]
新的教程:
[这里](https://github.com/Physics365/991CN-X-CW-Decompilation/blob/main/ROP/ROPCodes/Examples/Persistence/DataPersistence.md)
