### ISSUE TITLE
光标显示问题

### ISSUE THREAD

**Issue by Physics365** [Physics365/991CN-X-CW-Decompilation#39]
在教程中，需要添加实体机上显示的样式。

使用现在的字体，光标自己算一个字符，和后面的字符会有间距，不符合实际情况，怎么办呢？

类似于这样：

现在的效果：1| 2
希望的效果：1|2

**Comment by Wenti-D** [comment]
我考虑过了，[v3.002 的更新加了这一项](https://github.com/Wenti-D/ClasswizDisplayFont/releases/tag/disp-v3.002-x-cw)，用法是在 Word 中选中光标字符，然后选择【字体】→【文本效果和版式】→【样式集】→【个人】即可。
![image](https://github.com/Physics365/991CN-X-CW-Decompilation/assets/73067578/cf56628a-c435-462b-8708-de3cbcac3469)

**Comment by Physics365** [comment]
感谢，我的 Word 不是在这里设置的，但是在另一个设置里成功了。
